[dependencies]

[package]
  cjc-version = "0.53.18"
  compile-option = ""
  description = ""
  link-option = ""
  name = "cj_money"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "0.3.0"
  package-configuration = {}
